version: "3.9"
services:
  database:
    image: postgres
    networks:
      - backend
    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    networks:
      - backend
      - frontend
    expose:
      - 8000
    environment:
      - POSTGRES_NAME=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    depends_on:
      - database
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    networks:
      - frontend
    expose:
      - 80
    ports:
      - "80:80"
    depends_on:
      - backend
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
