FROM alpine:latest AS build
WORKDIR /app
RUN apk update && apk add git
RUN git clone https://github.com/dmzotov-ru/docker_homework.git

FROM python:3.9
WORKDIR /app
COPY --from=build /app/docker_homework/lib_catalog/ ./
RUN pip install -r requirements.txt
COMMAND: bash -c "python manage.py migrate; python manage.py loaddata bbk_data.json" 
ENTRYPOINT [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
